<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>edu.umg.programacion2</groupId>
        <artifactId>proyecto-empleados</artifactId>
        <version>1.0.0</version>
    </parent>

    <!-- Este módulo es la "librería": modelo + DAO. No sabe que existe Swing. -->
    <artifactId>proyecto-empleados-core</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Único dependencia externa real de este módulo: el driver JDBC de MySQL/MariaDB.
             La UI NUNCA declara esta dependencia directamente; le llega de forma transitiva
             a través de -core, pero la UI tampoco importa java.sql.* -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.33</version>
        </dependency>
    </dependencies>

</project>
